name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:  # This workflow performs the following steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - name: Set up JDK 11
        uses: actions/setup-java@v2 # The setup-java step configures the Java 11 JDK by Adoptium.
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven  # The "Build with Maven" step runs the Maven package target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
        run: mvn --batch-mode --update-snapshots verify
